SELECT * 
FROM MUSTERI 
INNER JOIN SIPARIS ON musterý.ýd=sýparýs.musterýno 
WHERE SIPARIS.DURUM=1;


SELECT MUSTERI.*,sýparýs.no,sýparýs.sepetfýyat 
FROM MUSTERI 
INNER JOIN SIPARIS ON musterý.ýd=sýparýs.musterýno 
INNER JOIN SIPARIS_DURUM ON SIPARIS_DURUM.DURUMKODU=sýparýs.durum AND SIPARIS_DURUM.ACIKLAMA='Teslim Edildi';


SELECT M.ID,M.AD,M.SOYAD,SD.ACIKLAMA,COUNT(S.NO) AS SIPARIS_SAYISI
FROM MUSTERI M
INNER JOIN SIPARIS S ON M.ID=s.musterýno
INNER JOIN SIPARIS_DURUM SD ON S.DURUM=SD.DURUMKODU
GROUP BY M.ID,M.AD,M.SOYAD,SD.ACIKLAMA
ORDER BY M.ID;

SELECT u.ad,U.FIYAT FROM URUN U 
JOIN (SELECT M.ID,M.AD,M.SOYAD,SD.URUNNO AS URUNKODU,COUNT(S.NO) AS SIPARIS_SAYISI
FROM MUSTERI M
INNER JOIN SIPARIS S ON M.ID=s.musterýno
INNER JOIN SIPARIS_DETAY SD ON S.NO=SD.SIPARISNO
GROUP BY M.ID,M.AD,M.SOYAD,SD.URUNNO
)T
ON T.URUNKODU=U.NO 
WHERE U.FIYAT > 25;


